version: '2'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - "./mosquitto:/mosquitto"
    restart: always
    ports:
      - "1883:1883"

volumes:
  mosquitto: