version: '2'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - "./mosquitto:/mosquitto"
    restart: always
    ports:
      - "1887:1887/tcp"
volumes:
  mosquitto: