version: "2"
services:
  server:
#    image: "jacobdevecomp/pbl_redes2:local_server-server"
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    network_mode:
      "host"